apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

patchesStrategicMerge:
- Deployment-patch.yaml

# The presence of the following VAR, will cause `command: null` to appear in final output
vars:
- name: SELECTOR
  objref:
    kind: Deployment
    name: deployment
    apiVersion: apps/v1
  fieldref:
    fieldpath: spec.selector.matchLabels.app